export interface ArchitectureData {
  id: string,
  imagemBase: string,
  titulo: string,
  subtitulo: string,
  localizacao: string,
  cliente: string,
  area: string,
  tamanho: string,
  programa: string,
  design: string,
  construcao: string,
  tipos: string,
  reconhecimentoDesign: string,
  bibliografia: string,
  descricao: string,
  sustentabilidade: string,
  imagens: string[],
  desenhos: string[],
  modelos: string[]
} 